# Changes here will be overwritten by Copier
_commit: v0.2.3
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage indexer
distribution_name: swh-indexer
have_cli: true
have_workers: true
package_root: swh/indexer
project_name: swh.indexer
python_minimal_version: '3.7'
readme_format: rst
